language: python

python:
  - 2.7
  - 3.5

env:
  - DJANGO: django>=1.8,<1.9
  - DJANGO: django>=1.9,<1.10
  - DJANGO: django>=1.10

before_install:
  - pip install codecov

install:
  - pip install $DJANGO
  - pip install -e .

script:
  - coverage run runtests.py

after_success:
  - codecov
