language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO: django>=1.8,<1.9
  - DJANGO: django>=1.9,<1.10
  - DJANGO: django>=1.10,<1.11
  - DJANGO: django>=1.11,<2.0
  - DJANGO: django>=2.0

before_install:
  - pip install codecov

install:
  - pip install $DJANGO
  - pip install -e .

script:
  - coverage run runtests.py

after_success:
  - codecov
